version: '3'

services:
  web:
    build: .
    entrypoint: bash start
    ports:
        - 8000:8000
    environment:
      DEBUG: 'true'
    volumes:
      - .:/app
    network_mode: host

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
